
on: [push, pull_request]

name: windows
jobs:

  ##################
  # Windows x86_64 #
  ##################

  Windows:
    name: Windows
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
          persist-credentials: false

    - name: Install Conda
      uses: goanpeca/setup-miniconda@v1
      with:
          auto-update-conda: true
          python-version: 3.8

    - name: Setup Conda
      run: conda -h && conda create -n revenge python==3.8.2 && conda activate revenge && pip install requests

    - name: Install radare2
      run: conda activate revenge && python tests/windows/setup_windows_test_env.py
    
    - name: Add r2 to PATH
      run: echo "C:\Radare2\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

    - name: Setup MSVC Environment
      uses: ilammy/msvc-dev-cmd@v1.2.0

    - name: Install angr
      shell: cmd
      run: conda activate revenge && git clone https://github.com/angr/angr-dev.git && cd angr-dev && git clone https://github.com/angr/vex.git && cd vex && nmake /f Makefile-msvc pub\libvex_guest_offsets.h && cd .. && setup.bat && pip install https://github.com/angr/angr-targets/archive/master.zip

    - name: Install revenge
      run: conda activate revenge && pip install .[dev]

    - name: Run tests
      shell: cmd
      run: conda activate revenge && pytest -v tests/windows


# set PATH=C:\Users\IEUser\miniconda3;C:\Users\IEUser\miniconda3\Library\mingw-w64\bin;C:\Users\IEUser\miniconda3\Library\usr\bin;C:\Users\IEUser\miniconda3\Library\bin;C:\Users\IEUser\miniconda3\Scripts;C:\Users\IEUser\miniconda3\bin;C:\Users\IEUser\miniconda3\condabin;%PATH% && call conda.bat init cmd.exe 
# # nmake /f Makefile-msvc pub\libvex_guest_offsets.h
